<script setup lang="ts">
import dayjs from 'dayjs'
import { toast } from 'vue-sonner'
import { z } from 'zod'
import type { Kebun } from '~/types'
const auth=useAuthStore();const{db,seed,audit}=useDatabase();const rows=ref<Kebun[]>([]),show=ref(false),editing=ref<number>(),search=ref(''),saving=ref(false),deletingId=ref<number>()
const form=reactive({idkebun:'',nama:'',pic:'',handphone:'',alamat:'',status:'Aktif' as Kebun['status']})
const permission=computed(()=>auth.user?.permissions.kebun);const superadmin=computed(()=>auth.user?.role==='superadmin');const canCreate=computed(()=>(superadmin.value||auth.user?.role==='admin')&&(superadmin.value||permission.value?.create));const canUpdate=computed(()=>superadmin.value||permission.value?.update);const canDelete=computed(()=>superadmin.value||permission.value?.delete)
const filtered=computed(()=>rows.value.filter(row=>`${row.nama} ${row.pic} ${row.handphone} ${row.alamat}`.toLowerCase().includes(search.value.toLowerCase())))
async function load(){await seed();rows.value=await db.kebun.toArray()}
function open(row?:Kebun){if(row&&!canUpdate.value)return toast.error('Tidak memiliki izin update');if(!row&&!canCreate.value)return toast.error('Tidak memiliki izin create');editing.value=row?.id===undefined?undefined:Number(row.id);Object.assign(form,row?{idkebun:row.idkebun,nama:row.nama,pic:row.pic,handphone:row.handphone,alamat:row.alamat,status:row.status}:{idkebun:crypto.randomUUID(),nama:'',pic:'',handphone:'',alamat:'',status:'Aktif'});show.value=true}
async function save(){if(saving.value)return;const isEditing=editing.value!==undefined;const result=z.object({idkebun:z.uuid(),nama:z.string().trim().min(3,'Nama minimal 3 karakter'),pic:z.string().trim().min(3,'PIC minimal 3 karakter'),handphone:z.string().trim().min(1,'Handphone wajib diisi').min(8,'Handphone minimal 8 digit').regex(/^[0-9+ -]+$/,'Format handphone tidak valid'),alamat:z.string().trim().min(5,'Alamat minimal 5 karakter'),status:z.enum(['Aktif','Nonaktif'])}).safeParse(form);if(!result.success){notifyValidationErrors(result.error);return}saving.value=true;try{const now=dayjs().toISOString(),actor=auth.user?.email||'system';if(isEditing){const old=await db.kebun.get(editing.value!);if(!old)throw new Error('Data kebun tidak ditemukan');await db.kebun.update(editing.value!,{...result.data,createdBy:old.createdBy,createdAt:old.createdAt,updatedBy:actor,updatedAt:now})}else await db.kebun.add({...result.data,createdBy:actor,createdAt:now});await audit(isEditing?'UPDATE':'CREATE','Kebun',form.nama);await load();show.value=false;toast.success(isEditing?'Kebun berhasil diperbarui':'Kebun berhasil ditambahkan')}catch(error){toast.error(error instanceof Error?error.message:'Kebun gagal disimpan')}finally{saving.value=false}}
async function remove(row:Kebun){if(!canDelete.value)return toast.error('Tidak memiliki izin delete');if(!confirm(`Hapus kebun ${row.nama}? Tindakan ini tidak dapat dibatalkan.`))return;deletingId.value=row.id;try{await db.kebun.delete(Number(row.id));await audit('DELETE','Kebun',row.nama);await load();toast.success('Kebun berhasil dihapus')}catch(error){toast.error(error instanceof Error?error.message:'Kebun gagal dihapus')}finally{deletingId.value=undefined}}
onMounted(load)
</script>
<template>
  <div>
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-2xl font-bold">Data Kebun</h2><p class="text-sm text-slate-500">Kelola data kebun operasional.</p></div><button v-if="canCreate" class="btn-primary" @click="open()">＋ Kebun</button></div>
    <div class="card overflow-hidden">
      <div class="border-b p-4"><input v-model="search" class="input max-w-sm" placeholder="Cari nama, PIC, handphone, atau alamat..."></div>
      <div class="overflow-x-auto"><table class="min-w-[1200px] w-full text-left text-sm">
        <thead class="bg-slate-50 text-xs uppercase text-slate-400"><tr><th v-for="h in ['No','Nama','PIC','Handphone','Alamat','Status','Aksi']" :key="h" class="px-5 py-3">{{h}}</th></tr></thead>
        <tbody><tr v-for="(row,idx) in filtered" :key="row.id" class="border-t align-top hover:bg-slate-50"><td class="px-5 py-4 text-ocean-600">{{idx+1}}</td><td class="px-5 py-4 font-semibold">{{row.nama}}</td><td class="px-5 py-4">{{row.pic}}</td><td class="px-5 py-4">{{row.handphone}}</td><td class="max-w-64 px-5 py-4 text-slate-500">{{row.alamat}}</td><td class="px-5 py-4"><span :class="row.status==='Aktif'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'" class="rounded-full px-2.5 py-1 text-xs font-semibold">{{row.status}}</span></td><td class="px-5 py-4"><div class="mb-3 whitespace-nowrap text-xs text-slate-400"><p><b>Created:</b> {{row.createdBy}}</p><p>{{dayjs(row.createdAt).format('DD/MM/YYYY HH:mm:ss')}}</p><template v-if="row.updatedAt"><p class="mt-2"><b>Updated:</b> {{row.updatedBy}}</p><p>{{dayjs(row.updatedAt).format('DD/MM/YYYY HH:mm:ss')}}</p></template></div><div class="flex gap-3"><button v-if="canUpdate" class="font-medium text-ocean-600" @click="open(row)">Update</button><button v-if="canDelete" class="font-medium text-red-500" :disabled="deletingId===row.id" @click="remove(row)">{{deletingId===row.id?'Menghapus...':'Delete'}}</button><span v-if="!canUpdate&&!canDelete" class="text-xs text-slate-400">Hanya lihat</span></div></td></tr><tr v-if="!filtered.length"><td colspan="7" class="p-10 text-center text-slate-400">Belum ada data Kebun</td></tr></tbody>
      </table></div>
    </div>
    <div v-if="show" class="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" @click.self="show=false"><form class="card w-full max-w-2xl p-6" @submit.prevent="save"><h3 class="mb-5 text-xl font-bold">{{editing!==undefined?'Update':'Tambah'}} Kebun</h3><div class="grid gap-4 sm:grid-cols-2"><input v-model="form.idkebun" type="hidden"><input v-model="form.nama" class="input" placeholder="Nama"><input v-model="form.pic" class="input" placeholder="PIC"><input v-model="form.handphone" class="input" placeholder="Handphone"><select v-model="form.status" class="input"><option>Aktif</option><option>Nonaktif</option></select><textarea v-model="form.alamat" class="input sm:col-span-2" placeholder="Alamat"></textarea></div><div class="mt-6 flex justify-end gap-3"><button type="button" class="btn-secondary" :disabled="saving" @click="show=false">Batal</button><button type="submit" class="btn-primary" :disabled="saving">{{saving?(editing!==undefined?'Mengupdate...':'Menyimpan...'):(editing!==undefined?'Update':'Simpan')}}</button></div></form></div>
  </div>
</template>
