<script setup lang="ts">
import dayjs from 'dayjs'
import { toast } from 'vue-sonner'
import { z } from 'zod'
import type { User, UserRole } from '~/types'
import { permissionsForRole } from '~/utils/menu'
import { phoneSchema } from '~/utils/identifier'
const {db,seed,audit}=useDatabase();const auth=useAuthStore();const rows=ref<User[]>([]);const search=ref('');const show=ref(false);const editing=ref<number>()
const form=reactive({iduser:'',email:'',name:'',handphone:'',alamat:'',role:'admin' as Exclude<UserRole,'superadmin'>,status:'Aktif' as User['status']})
const temporaryPassword=ref('')
const canReset=computed(()=>auth.user?.role==='superadmin'||auth.user?.role==='admin')
const filtered=computed(()=>rows.value.filter(user=>`${user.iduser} ${user.email} ${user.name} ${user.handphone}`.toLowerCase().includes(search.value.toLowerCase())))
const actorEmail=computed(()=>auth.user?.email||'admin@transmore.id')
async function load(){await seed();rows.value=await db.users.toArray()}
function open(user?:User){if(user?.role==='superadmin')return toast.error('Superadmin hanya dapat dikelola langsung melalui database');editing.value=user?.id;Object.assign(form,user?{iduser:user.iduser,email:user.email,name:user.name,handphone:user.handphone,alamat:user.alamat,role:user.role,status:user.status}:{iduser:crypto.randomUUID(),email:'',name:'',handphone:'',alamat:'',role:'admin',status:'Aktif'});show.value=true}
async function save(){const result=z.object({iduser:z.uuid('No harus berupa UUID'),email:z.email('Email tidak valid').transform(value=>value.trim().toLowerCase()),name:z.string().min(3,'Nama minimal 3 karakter'),handphone:phoneSchema,alamat:z.string().min(5,'Alamat minimal 5 karakter'),role:z.enum(['admin','driver']),status:z.enum(['Aktif','Nonaktif'])}).safeParse(form);if(!result.success)return toast.error(result.error.issues[0]?.message??'Data tidak valid');try{if(editing.value){const existing=await db.users.get(editing.value);if(!existing||existing.role==='superadmin')return toast.error('Superadmin tidak dapat diubah');await db.users.update(editing.value,{...result.data,permissions:existing.permissions})}else{const created=await db.users.add({...result.data,permissions:permissionsForRole(result.data.role)}) as {password?:string}|undefined;temporaryPassword.value=created?.password||''}await audit(editing.value?'UPDATE':'CREATE','Users',`${form.iduser} - ${form.email}`);show.value=false;toast.success('Pengguna berhasil disimpan');await load()}catch(error){toast.error(error instanceof Error?error.message:'No, email, atau nomor HP sudah digunakan')}}
async function resetPassword(user:User){if(!canReset.value||user.role==='superadmin')return toast.error('Reset password tidak diizinkan');if(!confirm(`Reset password ${user.name}?`))return;const response=await useApi().request<{password:string}>(`/users/${user.id}/reset-password`,{method:'POST'});temporaryPassword.value=response.data?.password||'';await audit('RESET PASSWORD','Users',user.email);toast.success('Password sementara berhasil dibuat');await load()}
async function copyTemporary(){await navigator.clipboard.writeText(temporaryPassword.value);toast.success('Password disalin')}
async function remove(user:User){if(user.role==='superadmin')return toast.error('Superadmin tidak dapat dihapus');if(!confirm(`Hapus ${user.name}?`))return;await db.users.delete(user.id!);await audit('DELETE','Users',`${user.iduser} - ${user.email}`);toast.success('Pengguna dihapus');await load()}
onMounted(load)
</script>
<template>
<div><div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-2xl font-bold">Manajemen Pengguna</h2><p class="text-sm text-slate-500">Kelola akun admin dan driver. Superadmin dilindungi oleh sistem.</p></div><button class="btn-primary" @click="open()">＋ User</button></div>
<div class="card overflow-hidden"><div class="border-b p-4"><input v-model="search" class="input max-w-sm" placeholder="Cari ID, email, nama, atau handphone..."></div><div class="overflow-x-auto"><table class="min-w-[1400px] w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-400"><tr><th v-for="header in ['No','Email','Nama','Handphone','Alamat','Role','Status','Aksi']" :key="header" class="px-5 py-3">{{header}}</th></tr></thead><tbody><tr v-for="(user, idx) in filtered" :key="user.id" class="border-t align-top hover:bg-slate-50"><td class="px-5 py-4 font-semibold text-ocean-600">{{idx + 1}}</td><td class="px-5 py-4">{{user.email}}</td><td class="px-5 py-4 font-medium">{{user.name}}</td><td class="px-5 py-4">{{user.handphone||'-'}}</td><td class="max-w-52 px-5 py-4 text-slate-500">{{user.alamat||'-'}}</td><td class="px-5 py-4"><span class="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold capitalize text-blue-700">{{user.role}}</span></td><td class="px-5 py-4"><span :class="user.status==='Aktif'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'" class="rounded-full px-2.5 py-1 text-xs font-semibold">{{user.status}}</span></td><td class="px-5 py-4"><div class="mb-3 whitespace-nowrap text-xs text-slate-400"><p><b>Created:</b> {{user.createdBy}}</p><p>{{dayjs(user.createdAt).format('DD/MM/YYYY HH:mm:ss')}}</p><template v-if="user.updatedAt"><p class="mt-2"><b>Updated:</b> {{user.updatedBy}}</p><p>{{dayjs(user.updatedAt).format('DD/MM/YYYY HH:mm:ss')}}</p></template></div><div v-if="user.role!=='superadmin'" class="flex gap-3"><button class="font-medium text-ocean-600" @click="open(user)">Update</button><button class="font-medium text-red-500" @click="remove(user)">Delete</button><button v-if="canReset" class="whitespace-nowrap rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-700 hover:bg-amber-100" @click="resetPassword(user)">Reset Password</button></div><span v-else class="text-xs font-semibold text-amber-600">Akun sistem dilindungi</span></td></tr><tr v-if="!filtered.length"><td colspan="8" class="p-10 text-center text-slate-400">Tidak ada pengguna yang sesuai</td></tr></tbody></table></div></div>
<div v-if="show" class="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/50 p-4" @click.self="show=false"><form class="card w-full max-w-2xl p-6" @submit.prevent="save"><h3 class="mb-5 text-xl font-bold">{{editing?'Update':'Tambah'}} Pengguna</h3><div class="grid gap-4 sm:grid-cols-2"><input type="hidden" v-model="form.iduser"><div><label class="label">Email</label><input v-model="form.email" type="email" class="input"></div><div><label class="label">Nama</label><input v-model="form.name" class="input"></div><div><label class="label">Handphone</label><input v-model="form.handphone" class="input" inputmode="tel"></div><div class="sm:col-span-2"><label class="label">Alamat</label><textarea v-model="form.alamat" class="input" rows="3"></textarea></div><div><label class="label">Role</label><select v-model="form.role" class="input"><option value="admin">Admin</option><option value="driver">Driver</option></select></div><div><label class="label">Status</label><select v-model="form.status" class="input"><option>Aktif</option><option>Nonaktif</option></select></div></div><div class="mt-6 flex justify-end gap-3"><button type="button" class="btn-secondary" @click="show=false">Batal</button><button class="btn-primary">{{editing?'Update':'Simpan'}}</button></div></form></div><div v-if="temporaryPassword" class="fixed inset-0 z-[60] grid place-items-center bg-slate-950/60 p-4"><div class="card w-full max-w-md p-6"><p class="text-xs font-bold uppercase text-amber-600">Password Sementara</p><h3 class="mt-2 text-xl font-bold">Simpan password ini</h3><p class="mt-2 text-sm text-slate-500">Password hanya ditampilkan sekali. Pengguna wajib menggantinya saat login.</p><div class="mt-5 flex items-center gap-3 rounded-xl bg-slate-100 p-4"><code class="flex-1 text-center text-2xl font-bold tracking-widest">{{temporaryPassword}}</code><button class="btn-secondary" @click="copyTemporary">Salin</button></div><button class="btn-primary mt-5 w-full" @click="temporaryPassword=''">Selesai</button></div></div></div>
</template>
